# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='arb_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arb_pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_location', models.CharField(max_length=200)),
                ('hotel_avg_budget', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='time_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='arb_options',
            name='arb_hotel_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.hotel_options'),
        ),
        migrations.AddField(
            model_name='arb_options',
            name='arb_time_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.time_options'),
        ),
        migrations.AddField(
            model_name='arb_options',
            name='arb_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
