# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arb_options',
            name='arb_hotel_options',
        ),
        migrations.RemoveField(
            model_name='arb_options',
            name='arb_time_options',
        ),
    ]
