# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180310_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arb_options',
            name='arb_user',
        ),
        migrations.AddField(
            model_name='arb_options',
            name='arb_hotel_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.hotel_options'),
        ),
    ]
