# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180311_0349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='arb_options',
            new_name='arb_option',
        ),
        migrations.RenameModel(
            old_name='hotel_options',
            new_name='hotel_option',
        ),
        migrations.RenameModel(
            old_name='time_options',
            new_name='time_option',
        ),
    ]
