# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180311_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arb_option',
            old_name='arb_hotel_options',
            new_name='arb_hotel_option',
        ),
    ]
