# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180311_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='arb_option',
            name='arb_time_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.time_option'),
        ),
    ]
